In [1]:
pip install PyGithub

Requirement already satisfied: PyGithub in /Users/erikahoshino/opt/anaconda3/lib/python3.8/site-packages (1.55)
Requirement already satisfied: pyjwt>=2.0 in /Users/erikahoshino/opt/anaconda3/lib/python3.8/site-packages (from PyGithub) (2.3.0)
Requirement already satisfied: requests>=2.14.0 in /Users/erikahoshino/opt/anaconda3/lib/python3.8/site-packages (from PyGithub) (2.25.1)
Requirement already satisfied: deprecated in /Users/erikahoshino/opt/anaconda3/lib/python3.8/site-packages (from PyGithub) (1.2.13)
Requirement already satisfied: pynacl>=1.4.0 in /Users/erikahoshino/opt/anaconda3/lib/python3.8/site-packages (from PyGithub) (1.4.0)
Requirement already satisfied: six in /Users/erikahoshino/opt/anaconda3/lib/python3.8/site-packages (from pynacl>=1.4.0->PyGithub) (1.15.0)
Requirement already satisfied: cffi>=1.4.1 in /Users/erikahoshino/opt/anaconda3/lib/python3.8/site-packages (from pynacl>=1.4.0->PyGithub) (1.14.5)
Requirement already satisfied: pycparser in /Users/erikahoshino/opt/anaconda3/lib/python3.8/site-packages (from cffi>=1.4.1->pynacl>=1.4.0->PyGithub) (2.20)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/erikahoshino/opt/anaconda3/lib/python3.8/site-packages (from requests>=2.14.0->PyGithub) (1.26.4)
Requirement already satisfied: chardet<5,>=3.0.2 in /Users/erikahoshino/opt/anaconda3/lib/python3.8/site-packages (from requests>=2.14.0->PyGithub) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /Users/erikahoshino/opt/anaconda3/lib/python3.8/site-packages (from requests>=2.14.0->PyGithub) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /Users/erikahoshino/opt/anaconda3/lib/python3.8/site-packages (from requests>=2.14.0->PyGithub) (2020.12.5)
Requirement already satisfied: wrapt<2,>=1.10 in /Users/erikahoshino/opt/anaconda3/lib/python3.8/site-packages (from deprecated->PyGithub) (1.12.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
from github import Github

g = Github("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")

# Github Enterprise with custom hostname
g = Github(base_url="https://{hostname}/api/v3", login_or_token="access_token")

In [3]:
from github.MainClass import Github
g = Github("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")

In [4]:
repo = g.get_repo("CSSEGISandData/COVID-19")
repo

Repository(full_name="CSSEGISandData/COVID-19")

In [5]:
file_list = repo.get_contents("csse_covid_19_data/csse_covid_19_daily_reports")

In [6]:
github_dir_path = 'https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_daily_reports/'
file_path = github_dir_path  + str(file_list[-2]).split('/')[-1].split(".")[0]+ '.csv'

In [17]:
import pandas as pd
from urllib.error import HTTPError
df = pd.read_csv(file_path, error_bad_lines=False)
df

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-01 05:23:07,33.93911,67.709953,52330,2189,41727,8414,Afghanistan,134.426484,4.183069
1,NaN,NaN,NaN,Albania,2021-01-01 05:23:07,41.15330,20.168300,58316,1181,33634,23501,Albania,2026.409062,2.025173
2,NaN,NaN,NaN,Algeria,2021-01-01 05:23:07,28.03390,1.659600,99610,2756,67127,29727,Algeria,227.155372,2.766790
3,NaN,NaN,NaN,Andorra,2021-01-01 05:23:07,42.50630,1.521800,8049,84,7432,533,Andorra,10417.394681,1.043608
4,NaN,NaN,NaN,Angola,2021-01-01 05:23:07,-11.20270,17.873900,17553,405,11044,6104,Angola,53.407342,2.307298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3996,NaN,NaN,W.P. Kuala Lumpur,Malaysia,2021-01-01 05:23:07,3.13900,101.686900,13488,22,8246,5220,"W.P. Kuala Lumpur, Malaysia",758.434548,0.163108
3997,NaN,NaN,W.P. Labuan,Malaysia,2021-01-01 05:23:07,5.28310,115.230800,1700,8,1591,101,"W.P. Labuan, Malaysia",1710.261569,0.470588
3998,NaN,NaN,W.P. Putrajaya,Malaysia,2021-01-01 05:23:07,2.92640,101.696400,281,3,239,39,"W.P. Putrajaya, Malaysia",266.603416,1.067616
3999,NaN,NaN,Unknown,Malaysia,2021-01-01 05:23:07,NaN,NaN,0,0,0,0,"Unknown, Malaysia",NaN,NaN
4000,NaN,NaN,NaN,Tonga,2021-01-01 05:23:07,-21.17900,-175.198200,0,0,0,0,Tonga,0.000000,NaN

In [18]:
try:
    years = [2021]
    months = [month for month in range(11, 13)]
    days = [day for day in range(1, 31)]
    URL = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports'
    all_files = []
    for year in years:
        for month in months:
            month = str(month).zfill(2)
            for day in days:
                day = str(day).zfill(2)
                print(f"{month}-{day}-{year}.csv")
                df = pd.read_csv(URL + f"/{month}-{day}-{year}.csv")
                all_files.append(df)
            final_csv_file = pd.concat(all_files, axis=0, ignore_index=True)
except HTTPError:
    pass

11-01-2021.csv
11-02-2021.csv
11-03-2021.csv
11-04-2021.csv
11-05-2021.csv
11-06-2021.csv
11-07-2021.csv
11-08-2021.csv
11-09-2021.csv
11-10-2021.csv
11-11-2021.csv
11-12-2021.csv
11-13-2021.csv
11-14-2021.csv
11-15-2021.csv
11-16-2021.csv
11-17-2021.csv
11-18-2021.csv
11-19-2021.csv
11-20-2021.csv
11-21-2021.csv
11-22-2021.csv
11-23-2021.csv
11-24-2021.csv
11-25-2021.csv
11-26-2021.csv
11-27-2021.csv
11-28-2021.csv
11-29-2021.csv
11-30-2021.csv
12-01-2021.csv
12-02-2021.csv
12-03-2021.csv
12-04-2021.csv
12-05-2021.csv
12-06-2021.csv
12-07-2021.csv
12-08-2021.csv
12-09-2021.csv
12-10-2021.csv
12-11-2021.csv
12-12-2021.csv
12-13-2021.csv
12-14-2021.csv
12-15-2021.csv
12-16-2021.csv

In [14]:
print(df)

      FIPS Admin2 Province_State      Country_Region          Last_Update  \
0      NaN    NaN            NaN         Afghanistan  2021-12-16 04:22:11
1      NaN    NaN            NaN             Albania  2021-12-16 04:22:11
2      NaN    NaN            NaN             Algeria  2021-12-16 04:22:11
3      NaN    NaN            NaN             Andorra  2021-12-16 04:22:11
4      NaN    NaN            NaN              Angola  2021-12-16 04:22:11
...    ...    ...            ...                 ...                  ...
4001   NaN    NaN            NaN             Vietnam  2021-12-16 04:22:11
4002   NaN    NaN            NaN  West Bank and Gaza  2021-12-16 04:22:11
4003   NaN    NaN            NaN               Yemen  2021-12-16 04:22:11
4004   NaN    NaN            NaN              Zambia  2021-12-16 04:22:11
4005   NaN    NaN            NaN            Zimbabwe  2021-12-16 04:22:11

            Lat       Long_  Confirmed  Deaths  Recovered  Active  \
0     33.939110   67.709953     157665    7331        NaN     NaN
1     41.153300   20.168300     204627    3152        NaN     NaN
2     28.033900    1.659600     213533    6165        NaN     NaN
3     42.506300    1.521800      20136     134        NaN     NaN
4    -11.202700   17.873900      65565    1737        NaN     NaN
...         ...         ...        ...     ...        ...     ...
4001  14.058324  108.277199    1459175   28616        NaN     NaN
4002  31.952200   35.233200     465094    4855        NaN     NaN
4003  15.552727   48.516388      10081    1973        NaN     NaN
4004 -13.133897   27.849332     212278    3671        NaN     NaN
4005 -19.015438   29.154857     177690    4745        NaN     NaN

            Combined_Key  Incident_Rate  Case_Fatality_Ratio
0            Afghanistan     405.013407             4.649732
1                Albania    7110.535826             1.540364
2                Algeria     486.950789             2.887142
3                Andorra   26060.959037             0.665475
4                 Angola     199.490249             2.649279
...                  ...            ...                  ...
4001             Vietnam    1499.071545             1.961108
4002  West Bank and Gaza    9116.958899             1.043875
4003               Yemen      33.799406            19.571471
4004              Zambia    1154.691624             1.729336
4005            Zimbabwe    1195.524946             2.670381

[4006 rows x 14 columns]